"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.wiki = void 0;
exports.wiki = {
    'wiki.ai.title': 'AI内容生成',
    'wiki.ai.insert_and_replace': '替换内容',
    'wiki.ai.insert_below': '插入内容',
    'wiki.ai.generate_result': '生成结果',
    'wiki.ai.stop': '停止',
    'wiki.ai.regenerate': '重新生成',
    'wiki.ai.ask_ai': '让AI编辑或生成内容',
    'wiki.ai.edit_or_review': '编辑或审阅文本',
    'wiki.ai.improve_writing': '改善文本',
    'wiki.ai.fix_spell': '修正拼写和语法',
    'wiki.ai.make_longer': '扩长内容',
    'wiki.ai.make_shorter': '缩短内容',
    'wiki.ai.generate_from_selection': '基于文本生成内容',
    'wiki.ai.list_action_items': '列出待办事项',
    'wiki.ai.summarize': '总结',
    'wiki.ai.briefly': '简要总结',
    'wiki.ai.exhaustively': '详细总结',
    'wiki.ai.translate': '翻译',
    'wiki.ai.translate_en': '英语',
    'wiki.ai.translate_ja': '日语',
    'wiki.ai.translate_zh': '中文',
    'wiki.ai.translate_thai': '泰语',
    'wiki.ai.continue_writing': '续写',
    'wiki.ai.next_paragraph': '下一段落',
    'wiki.ai.outline': '提纲',
    'wiki.ai.email': '邮件',
    'wiki.ai.blog_post': '博客文章',
    'wiki.ai.test_cases': '测试用例',
    'wiki.ai.requirement_doc': '需求文档',
    'wiki.ai.development_doc': '开发文档',
    'wiki.ai.pros_cons_list': '优劣势列表',
    'wiki.ai.help_guide': '帮助文档',
    'commonText.copy': '复制',
};
